services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  redis:
    image: redis:8.2.1
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis_data:/data
    command: "redis-server /usr/local/etc/redis/redis.conf"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
