services:
  postgres:
    image: postgres:15-alpine
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "/database/data:/var/lib/postgresql/data"
