services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "/database/data:/var/lib/postgresql/data"

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - /redis:/data
